### ISSUE TITLE
Démo HS

### ISSUE THREAD

**Issue by A973C** [GregOriol/covid-dashboard-france#1]
Bonjour @GregOriol 
Merci d'avoir partagé le calcul des indicateurs COVID. Seulement la démo est HS. Pourrais-tu y jeter un oeil stp ?
Merci à toi :)

**Comment by GregOriol** [comment]
Bonjour @A973C,

En effet, les données sont KO dans les CSV de data d'hier... on va voir si elles sont rétablies dans ceux qui seront publiés aujourd'hui ¯\_(ツ)_/¯

**Comment by GregOriol** [comment]
Ca a l'air résolu :-)

**Comment by A973C** [comment]
Je confirme ! Merci encore :)
